# main.py — Entry point, event loop, and rendering for Frogger

import sys
import os
import pygame
from config import *
from game import Game

# Audio file paths (generated by sub-agent)
AUDIO_DIR = os.path.join(os.path.dirname(__file__), "subagent-output", "assets")
BGM_PATH = os.path.join(AUDIO_DIR, "bgm_frogger.wav")
SFX_HOP_PATH = os.path.join(AUDIO_DIR, "sfx_hop.wav")
SFX_DEATH_PATH = os.path.join(AUDIO_DIR, "sfx_death.wav")
SFX_DING_PATH = os.path.join(AUDIO_DIR, "sfx_ding.wav")

# Initialize pygame mixer and load audio
pygame.mixer.init()
MIXER_VOLUME = 0.8  # 80% volume

bgm_music = None
sfx_hop = None
sfx_death = None
sfx_ding = None

try:
    bgm_music = pygame.mixer.Sound(BGM_PATH)
    bgm_music.set_volume(MIXER_VOLUME)
    print(f"🎵 BGM loaded from: {BGM_PATH}")
except Exception as e:
    print(f"⚠️ Failed to load BGM: {e}")

try:
    sfx_hop = pygame.mixer.Sound(SFX_HOP_PATH)
    sfx_hop.set_volume(MIXER_VOLUME)
    print("🔊 Hop sound loaded")
except Exception as e:
    print(f"⚠️ Failed to load hop sound: {e}")

try:
    sfx_death = pygame.mixer.Sound(SFX_DEATH_PATH)
    sfx_death.set_volume(MIXER_VOLUME)
    print("💀 Death sound loaded")
except Exception as e:
    print(f"⚠️ Failed to load death sound: {e}")

try:
    sfx_ding = pygame.mixer.Sound(SFX_DING_PATH)
    sfx_ding.set_volume(MIXER_VOLUME)
    print("🏠 Ding sound loaded")
except Exception as e:
    print(f"⚠️ Failed to load ding sound: {e}")

print("✅ Audio initialization complete!")


def draw_start_screen(screen):
    """Draw the game title / start screen."""
    # background
    screen.fill(BG_GRASS)
    # grid pattern (road-like)
    for y in range(0, CANVAS_HEIGHT, TILE_SIZE):
        pygame.draw.line(screen, (80, 80, 80), (0, y), (CANVAS_WIDTH, y), 2)

    # title
    font_big = pygame.font.SysFont(None, 72)
    title_surf = font_big.render("FROGGER", True, FROG_GREEN)
    rect = title_surf.get_rect(center=(CANVAS_WIDTH // 2, CANVAS_HEIGHT // 3))
    screen.blit(title_surf, rect)

    # subtitle
    font_med = pygame.font.SysFont(None, 36)
    sub = font_med.render("Press SPACE to Start", True, WHITE)
    r = sub.get_rect(center=(CANVAS_WIDTH // 2, CANVAS_HEIGHT // 2))
    screen.blit(sub, r)

    # instructions
    font_sm = pygame.font.SysFont(None, 24)
    inst = [
        "Arrow keys — Move the frog",
        "Reach the top slots to score!",
        "Avoid cars on the road,",
        "Ride logs across the river.",
    ]
    for i, line in enumerate(inst):
        txt = font_sm.render(line, True, WHITE)
        screen.blit(txt, (CANVAS_WIDTH // 2 - 80, CANVAS_HEIGHT * 0.65 + i * 24))


def draw_game_over_screen(screen):
    """Draw the game-over / lose screen."""
    screen.fill((30, 30, 30))
    font_big = pygame.font.SysFont(None, 72)
    txt = font_big.render("GAME OVER", True, CAR_RED)
    rect = txt.get_rect(center=(CANVAS_WIDTH // 2, CANVAS_HEIGHT // 3))
    screen.blit(txt, rect)

    font_med = pygame.font.SysFont(None, 36)
    sub = font_med.render("Press R to Retry", True, WHITE)
    r = sub.get_rect(center=(CANVAS_WIDTH // 2, CANVAS_HEIGHT // 2))
    screen.blit(sub, r)


def draw_win_screen(screen):
    """Draw the victory / win screen."""
    screen.fill((50, 80, 50))
    font_big = pygame.font.SysFont(None, 72)
    txt = font_big.render("YOU WIN!", True, FROG_GREEN)
    rect = txt.get_rect(center=(CANVAS_WIDTH // 2, CANVAS_HEIGHT // 3))
    screen.blit(txt, rect)

    font_med = pygame.font.SysFont(None, 36)
    sub = font_med.render("Press R to Play Again", True, WHITE)
    r = sub.get_rect(center=(CANVAS_WIDTH // 2, CANVAS_HEIGHT // 2))
    screen.blit(sub, r)


def main():
    pygame.init()
    screen = pygame.display.set_mode((CANVAS_WIDTH + 20, CANVAS_HEIGHT + 35))
    pygame.display.set_caption("Frogger")
    clock = pygame.time.Clock()

    # Pass sounds dict to Game for playback
    sounds_dict = {
        "sfx_hop": sfx_hop,
        "sfx_death": sfx_death,
        "sfx_ding": sfx_ding,
    }
    game = Game(sounds=sounds_dict)
    
    # Start background music (looping)
    if bgm_music:
        bgm_music.play(-1)  # Sound.play with loops=-1 loops forever
    running = True

    while running:
        events = pygame.event.get()
        for event in events:
            if event.type == pygame.QUIT:
                running = False

            # global key handling (outside gameplay)
            if event.type == pygame.KEYDOWN:
                if game.state == STATE_START and event.key == pygame.K_SPACE:
                    game.start_game()
                elif game.state in (STATE_GAMEOVER, STATE_WIN) and \
                        event.key == pygame.K_r:
                    game.state = STATE_START

        # handle gameplay input
        game.handle_input(events)

        # update game logic
        dt = clock.tick(FPS) / 1000.0   # seconds since last frame
        if game.state == STATE_PLAYING:
            game.update(dt)

        # render
        screen.fill(HUD_BG)   # clear entire screen to black
        game.draw(screen)
        game.draw_hud(screen)

        # overlay screens on top of canvas area
        if game.state == STATE_START:
            draw_start_screen(screen)
        elif game.state == STATE_GAMEOVER:
            draw_game_over_screen(screen)
        elif game.state == STATE_WIN:
            draw_win_screen(screen)

        pygame.display.flip()

    pygame.quit()
    sys.exit()


if __name__ == "__main__":
    main()
